### PR TITLE
Make code Python 2/3 agnostic #2

### PR DESCRIPTION
**Pull request by shubham7298**
Issue #2 resolved.

### CODE REVIEW

**Comment by vineetjc** [comment]
Some feedback:

- `urllib` is not there in Python 3. (https://stackoverflow.com/questions/17960942/attributeerror-module-object-has-no-attribute-urlretrieve). Hence even though the code runs on both Python 2 and 3, it won't download images on Python 3, and you won't notice errors because of a try-except block.

- A little surprised that you didn't notice that the images weren't being downloaded when using Python 3 (also check your terminal.png image, it only has one URL of an image printed and skips to the next year. 

- I would have merged this PR and then made the changes myself, but then that wouldn't mean anything to me, I think you should make the changes to the terminal.png images and check the StackOverflow link I suggested for solutions regarding `urllib`. (go below, there's an answer)

- Issue #2 will remain open till the end of KWoC to accommodate further changes.

Otherwise, awesome work overall @shubham7298!

**Comment by shubham7298** [comment]
Thank you @vineetjc for your mentorship. I will work on your advice.

**Comment by vineetjc** [comment]
@shubham7298 Great work! Merged the PR.

**Comment by vineetjc** [comment]
@shubham7298 one more feedback I have:

- It's important to briefly state whatever your PR does unless you'd have a lot of things and need to explain it as a comment in the description. Here, for instance, it's not just solving #2 but also gives a fix to #1. It's a very minor thing, I'll do it for now, but note next time on,

Awesome work!

**Pull request merged**
